# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7fd89f2943c71a73e718ab4f49dc030c92abc2f928ad27eb0bf69c57bc64de5f497506480c8aa11023029743f8333e05c7654ac795a1be9dca0395c79fcd2be2

test:
  secret_key_base: f7b5519a86774ab6f0d0905869d5ea3589e9ac4da220d7ef13fdc3bbbbedc774178330569ec6852e4fd1b198770b2eed16cf8e3ffd0b3e37e6da877eb01c6839

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
